spring.application.name=ecommerce-platform

server.port=8086
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerceproject
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

# --- Downstream service clients ---
clients.product-service.url=http://10.17.49.21:8080
clients.merchant-service.url=http://10.17.48.70:4001
clients.order-service.url=http://10.17.48.87:8085
clients.user-service.url=http://10.17.48.87:8082

spring.cloud.openfeign.circuitbreaker.enabled=true
feign.client.config.default.connectTimeout=2000
feign.client.config.default.readTimeout=2000

